apiVersion: v1
kind: ConfigMap
metadata:
  name: geektime-config
  namespace: default
data:
  VERSION: v1.0
[root@172.26.200.240 module08]# cat httpserver-deployment.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver-deployment
  labels:
    app: httpserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      containers:
      - name: httpserver
        image: httpserver:1.2
        command: ['./httpserver']
        env:
        - name: VERSION
          valueFrom:
            configMapKeyRef:  # 6.配置和代码分离
              name: geektime-config
              key: VERSION
        resources:  # 3.资源需求和 QoS Guaranteed
          limits:
            cpu: 700m
            memory: 200Mi
          requests:
            cpu: 700m
            memory: 200Mi
        ports:
        - containerPort: 80
        livenessProbe:  # 4.探活
          httpGet:
            path: /healthz
            port: 80
            httpHeaders:
            - name: X-Custom-Header
              value: Awesome
          initialDelaySeconds: 15
          timeoutSeconds: 1
        lifecycle:
          postStart:  # 1.优雅启动
            exec:
              command: ["/bin/sh","-c","echo this pod is starting. > /start.log && sleep 10s"]
          preStop:    # 2.优雅终止
            exec:
              command: ["/bin/sh","-c","echo this pod is stopping. > /stop.log && sleep 10s"]
